export * from "./ActivateAccount";
export * from "./Settings";
export * from "./Coordenadores";
export * from "./Dashboard";
export * from "./DashboardAdmin";
export * from "./DashboardCoordenador";
export * from "./DashboardDiretor";
export * from "./ForgotPassword";
export * from "./ManageUsers";
export * from "./Login";
export * from "./MyRequests";
export * from "./Professores";
export * from "./Register";
export * from "./RequestHae";
export * from "./ResetPassword";
export * from "./ContactUs";
export * from "./AllHaesByInstitution";
export * from "./ViewHae";
export * from "./CreateInstitution"
export * from "./DashboardDev"
export * from "./ListInstitutions"
export * from "./EditInstitution"
export * from "./AllHaes"
export * from "./RequestClosurePage"
export * from "./ClosureRequests"
export * from "./ApprovedHaes"
export * from "./ViewClosureRequest"